name: polygon
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.2
  shared_preferences: ^2.2.2
  flutter_slidable: ^4.0.0
  http: ^1.3.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  image_picker: ^1.0.7
  provider: ^6.1.2
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_email_sender: ^7.0.0
  cached_network_image: ^3.3.1
  firebase_app_check: ^0.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  fonts:
    - family: pupupu
      fonts:
        - asset: lib/fonts/pupupu-free.otf

  assets:
    - assets/polygon.jpg
    - assets/background.jpg
    - assets/paira.PNG
    - assets/small_paira.PNG
    - assets/sprash.png
    - assets/logo.png
    - assets/preimage.JPG
    - assets/preheader.jpg
    - assets/contract.txt
    - assets/privacy.txt

flutter_native_splash:
  image: assets/sprash.png
  color: "4472C4"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
